# -*- coding: utf-8 -*-
"""Data preparation - 27Sep2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vbu8YZbdh_33aAzPMI96EYYjtbi-cyW4

# Data Preprocessing and Feature Engineering

This section defines a `DataProcessor` class containing reusable functions to clean, transform, and engineer features from the application datasets. The goal is to apply the decisions made during the Exploratory Data Analysis consistently to both the training and test data.

## Imports & Datasets
"""

from google.colab import drive
import pandas as pd
import numpy as np

# Mount Google Drive (if needed for Colab):
drive.mount('/content/drive')

train_data = pd.read_csv("/content/drive/MyDrive/MSBA Practice Project/application_train.csv")
test_data = pd.read_csv("/content/drive/MyDrive/MSBA Practice Project/application_test.csv")

"""## Data Cleansing"""

class DataProcessor:
    """
    A class for cleaning, transforming, and engineering features for the Home Credit Default Risk dataset.

    The methods in this class are designed to ensure consistency between training and test datasets
    by fitting parameters (e.g., imputation values, columns to drop) on the training data only
    and then applying them to both. The decisions are based on the preceding EDA.
    """
    def __init__(self, high_missing_threshold=0.70):
        self.imputation_values = {}  # Stores median/mode for numerical/categorical imputation
        self.dropped_columns = []    # Stores columns identified to be dropped due to high missing % in train
        self.categorical_cols_with_missing_category = [
            'NAME_TYPE_SUITE', 'OCCUPATION_TYPE', 'FONDKAPREMONT_MODE',
            'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'
        ] # Categorical columns where 'Missing' will be a new category, based on EDA inspection
        self.high_missing_threshold = high_missing_threshold

    def _handle_xna_gender(self, df):
        """
        EDA Decision: Replaces 'XNA' values in 'CODE_GENDER' with NaN.
        """
        if 'CODE_GENDER' in df.columns:
            df['CODE_GENDER'] = df['CODE_GENDER'].replace('XNA', np.nan)
        return df

    def _handle_days_employed_outlier(self, df):
        """
        EDA Decision: Addresses the 365243 outlier in 'DAYS_EMPLOYED'.
        This value is an anomaly indicating an undocumented employment status.
        It's replaced with NaN, and a binary flag 'DAYS_EMPLOYED_ANOM' is created.
        """
        if 'DAYS_EMPLOYED' in df.columns:
            df['DAYS_EMPLOYED_ANOM'] = (df['DAYS_EMPLOYED'] == 365243).astype(int)
            df['DAYS_EMPLOYED'] = df['DAYS_EMPLOYED'].replace({365243: np.nan}) # Removed inplace=True
        return df

    def _drop_high_missing_columns(self, df):
        """
        EDA Decision: Drops columns with a very high percentage of missing values (defined by threshold).
        Columns to drop are identified during the `fit` phase on the training data.
        """
        if self.dropped_columns:
            df = df.drop(columns=self.dropped_columns, errors='ignore')
        return df

    def _create_missing_indicators(self, df):
        """
        EDA Decision: Creates binary indicators for columns that originally had missing values.
        This is done before imputation to capture the initial missingness.
        """
        # Ensure we only create indicators for columns that exist in the current df
        # and were identified as missing in the training data.
        for col in list(self.imputation_values.keys()): # Keys represent columns that had missing values in train
            if col in df.columns:
                # Only create indicator if the column still has NaNs before imputation
                # (e.g., if XNA was converted to NaN or original NaNs exist)
                if df[col].isnull().any():
                    df[col + '_IS_MISSING'] = df[col].isnull().astype(int)
        # Special handling for CODE_GENDER if it became NaN from XNA
        if 'CODE_GENDER' in df.columns and 'CODE_GENDER' not in self.dropped_columns and df['CODE_GENDER'].isnull().any():
             df['CODE_GENDER_IS_MISSING'] = df['CODE_GENDER'].isnull().astype(int)
        return df

    def _impute_missing_values(self, df):
        """
        EDA Decision: Imputes missing values using strategies determined during the `fit` phase.
        Numerical columns are imputed with the median; specific categorical columns get 'Missing'; others by mode.
        """
        for col in df.columns:
            if col in self.imputation_values: # Only impute for columns that had missing values in train
                if df[col].dtype in ['int64', 'float64']:
                    df[col] = df[col].fillna(self.imputation_values[col]) # Removed inplace=True
                elif df[col].dtype == 'object':
                    if col in self.categorical_cols_with_missing_category:
                        df[col] = df[col].fillna('Missing') # Removed inplace=True
                    else:
                        df[col] = df[col].fillna(self.imputation_values[col]) # Removed inplace=True
        return df

    def _engineer_demographic_features(self, df):
        """
        EDA Decision: Updates demographic features like age and employment duration.
        'DAYS_BIRTH' and 'DAYS_EMPLOYED' (after outlier handling) are converted to positive years.
        """
        if 'DAYS_BIRTH' in df.columns:
            df['AGE_YEARS'] = df['DAYS_BIRTH'] / -365
        if 'DAYS_EMPLOYED' in df.columns:
            df['EMPLOYMENT_YEARS'] = df['DAYS_EMPLOYED'] / -365
        return df

    def _engineer_financial_ratios(self, df):
        """
        EDA Decision: Adds financial ratios based on income, credit, and annuity amounts.
        """
        # Using a temporary copy for ratio calculations to prevent SettingWithCopyWarning
        # and ensure original columns are not modified unexpectedly within this method.
        temp_df_for_ratios = df.copy()

        if all(col in temp_df_for_ratios.columns for col in ['AMT_CREDIT', 'AMT_INCOME_TOTAL']):
            df['CREDIT_INCOME_RATIO'] = temp_df_for_ratios['AMT_CREDIT'] / temp_df_for_ratios['AMT_INCOME_TOTAL']
        if all(col in temp_df_for_ratios.columns for col in ['AMT_ANNUITY', 'AMT_INCOME_TOTAL']):
            df['ANNUITY_INCOME_RATIO'] = temp_df_for_ratios['AMT_ANNUITY'] / temp_df_for_ratios['AMT_INCOME_TOTAL']
        if all(col in temp_df_for_ratios.columns for col in ['AMT_CREDIT', 'AMT_ANNUITY']):
            df['CREDIT_ANNUITY_RATIO'] = temp_df_for_ratios['AMT_CREDIT'] / temp_df_for_ratios['AMT_ANNUITY']
        if all(col in temp_df_for_ratios.columns for col in ['AMT_GOODS_PRICE', 'AMT_CREDIT']):
            df['GOODS_PRICE_CREDIT_RATIO'] = temp_df_for_ratios['AMT_GOODS_PRICE'] / temp_df_for_ratios['AMT_CREDIT']
        if all(col in temp_df_for_ratios.columns for col in ['AMT_INCOME_TOTAL', 'CNT_FAM_MEMBERS']):
            df['INCOME_PER_PERSON'] = temp_df_for_ratios['AMT_INCOME_TOTAL'] / temp_df_for_ratios['CNT_FAM_MEMBERS']
            # Handle potential division by zero if CNT_FAM_MEMBERS is 0 after imputation (unlikely but good practice)
            df['INCOME_PER_PERSON'] = df['INCOME_PER_PERSON'].replace([np.inf, -np.inf], np.nan) # Removed inplace=True
            df['INCOME_PER_PERSON'] = df['INCOME_PER_PERSON'].fillna(df['AMT_INCOME_TOTAL']) # If members is 0, income per person is total income, Removed inplace=True
        return df

    def _create_binned_features(self, df):
        """
        EDA Decision: Creates binned features for 'AGE_YEARS' and 'CNT_CHILDREN'.
        """
        if 'AGE_YEARS' in df.columns:
            df['AGE_GROUP'] = pd.cut(df['AGE_YEARS'], bins=[0, 25, 35, 45, 55, 65, 100],
                                     labels=['<25', '25-34', '35-44', '45-54', '55-64', '65+'], right=False)
        if 'CNT_CHILDREN' in df.columns:
            df['CHILDREN_GROUP'] = pd.cut(df['CNT_CHILDREN'], bins=[-1, 0, 1, 2, df['CNT_CHILDREN'].max() + 1],
                                          labels=['No Children', '1 Child', '2 Children', '3+ Children'], right=True)
        return df

    def fit(self, X_train):
        """
        Fits the processor on the training data to learn parameters for transformations.
        This includes identifying columns to drop and calculating imputation values.
        """
        temp_df = X_train.copy() # Work on a copy to avoid modifying original during fit

        # 1. Handle specific outliers/conversions first
        temp_df = self._handle_xna_gender(temp_df)
        temp_df = self._handle_days_employed_outlier(temp_df)

        # 2. Identify columns to drop based on training data's missing percentage
        missing_percentage = temp_df.isnull().sum() * 100 / len(temp_df)
        self.dropped_columns = missing_percentage[missing_percentage > self.high_missing_threshold].index.tolist()

        # 3. Apply dropping *before* computing imputation values, to avoid using dropped columns
        temp_df = self._drop_high_missing_columns(temp_df)

        # 4. Compute and store imputation values for remaining columns
        for col in temp_df.columns:
            if temp_df[col].isnull().any():
                if temp_df[col].dtype in ['int64', 'float64']:
                    self.imputation_values[col] = temp_df[col].median()
                elif temp_df[col].dtype == 'object' and col not in self.categorical_cols_with_missing_category:
                    self.imputation_values[col] = temp_df[col].mode()[0] # Only for categorical not handled by 'Missing' category
        return self

    def transform(self, df):
        """
        Applies the learned transformations to a DataFrame (train or test).
        """
        df = df.copy()

        # Apply cleaning steps
        df = self._handle_xna_gender(df)
        df = self._handle_days_employed_outlier(df)
        df = self._drop_high_missing_columns(df) # Drop columns identified during fit

        # Create missing indicators before imputation
        df = self._create_missing_indicators(df)

        # Impute missing values using stored values from training data
        df = self._impute_missing_values(df)

        # Apply feature engineering steps
        df = self._engineer_demographic_features(df)
        df = self._engineer_financial_ratios(df) # Pass df directly, logic inside handles copying
        df = self._create_binned_features(df)

        return df

    def fit_transform(self, X_train):
        """
        Fits the processor on training data and then transforms it.
        """
        return self.fit(X_train).transform(X_train)

"""## Applying Data Preprocessing and Feature Engineering

Now, let's instantiate the `DataProcessor` and apply the defined cleaning and feature engineering steps to both the training and test datasets. We will first fit the processor on the training data (`app_train_df`) to learn necessary parameters (like columns to drop and imputation values), and then transform both datasets.
"""

# Load application_train.csv file to ensure app_train_df is defined
app_train_df = pd.read_csv('/content/drive/MyDrive/MSBA Practice Project/application_train.csv')

# Load application_test.csv file to ensure app_test_df is defined
app_test_df = pd.read_csv('/content/drive/MyDrive/MSBA Practice Project/application_test.csv')

# Make a copy of the original dataframes to work with, especially for the training set
app_train_processed = app_train_df.copy()
app_test_processed = app_test_df.copy()

# Separate TARGET from training data before processing features
if 'TARGET' in app_train_processed.columns:
    train_target = app_train_processed['TARGET']
    app_train_processed = app_train_processed.drop(columns=['TARGET'])
else:
    train_target = None # Should not happen for train_df

# Initialize the DataProcessor
data_processor = DataProcessor(high_missing_threshold=0.70)

# Fit the processor on the training data and transform it
print("Processing training data...")
app_train_processed = data_processor.fit_transform(app_train_processed)

# Transform the test data using the parameters learned from the training data
print("Processing test data...")
app_test_processed = data_processor.transform(app_test_processed)

# Re-add the TARGET column to the processed training data if it was present initially
if train_target is not None:
    app_train_processed['TARGET'] = train_target

print("\nProcessed Training Data Shape:", app_train_processed.shape)
print("Processed Test Data Shape:", app_test_processed.shape)

print("\nFirst 5 rows of Processed Training Data:")
display(app_train_processed.head())

print("\nFirst 5 rows of Processed Test Data:")
display(app_test_processed.head())

"""## Processing Supplementary Tables

This section focuses on processing the supplementary datasets (`bureau.csv`, `bureau_balance.csv`, `previous_application.csv`) to extract aggregated features. These features will then be merged with the main `app_train_processed` and `app_test_processed` dataframes to provide a more comprehensive view of the applicants' credit history and past interactions with Home Credit or other financial institutions. The goal is to create consistent features across both train and test sets.
"""

class SupplementaryProcessor:
    """
    A class to process and aggregate supplementary tables (bureau, bureau_balance, previous_application)
    and prepare them for merging with the main application data.
    """
    def __init__(self, data_path='/content/drive/MyDrive/MSBA Practice Project/'):
        self.data_path = data_path
        self.bureau = None
        self.bureau_balance = None
        self.previous_application = None
        self.bureau_aggregations = {}
        self.prev_app_aggregations = {}

    def _load_data(self):
        """
        Loads the supplementary datasets.
        """
        print("Loading supplementary data...")
        self.bureau = pd.read_csv(self.data_path + 'bureau.csv')
        self.bureau_balance = pd.read_csv(self.data_path + 'bureau_balance.csv')
        self.previous_application = pd.read_csv(self.data_path + 'previous_application.csv')
        print("Supplementary data loaded.")

    def _process_bureau_and_balance(self):
        """
        Processes bureau and bureau_balance tables.
        - One-hot encodes categorical features in bureau_balance.
        - Aggregates bureau_balance by SK_ID_BUREAU.
        - Merges aggregated bureau_balance into bureau.
        - One-hot encodes categorical features in bureau.
        - Aggregates bureau by SK_ID_CURR.
        """
        print("Processing Bureau and Bureau Balance data...")

        # --- Process bureau_balance ---
        # One-hot encode categorical features
        bb_categorical_cols = self.bureau_balance.select_dtypes('object').columns
        self.bureau_balance = pd.get_dummies(self.bureau_balance, columns=bb_categorical_cols, dummy_na=False)

        # Group by SK_ID_BUREAU and aggregate
        bb_aggregations = {
            'MONTHS_BALANCE': ['min', 'max', 'size'],
            **{col: ['mean'] for col in self.bureau_balance.columns if '_STATUS' in col}
        }
        bureau_by_loan = self.bureau_balance.groupby('SK_ID_BUREAU').agg(bb_aggregations)
        bureau_by_loan.columns = ['_'.join(col).strip() for col in bureau_by_loan.columns.values]

        # Merge with bureau
        self.bureau = self.bureau.merge(bureau_by_loan, on='SK_ID_BUREAU', how='left')
        self.bureau.drop(columns=['SK_ID_BUREAU'], inplace=True) # SK_ID_BUREAU is no longer needed after aggregation

        # --- Process bureau ---
        # One-hot encode categorical features
        bureau_categorical_cols = self.bureau.select_dtypes('object').columns
        self.bureau = pd.get_dummies(self.bureau, columns=bureau_categorical_cols, dummy_na=False)

        # Define aggregations for bureau
        bureau_aggregations = {
            'DAYS_CREDIT': ['min', 'max', 'mean', 'var'],
            'DAYS_CREDIT_ENDDATE': ['min', 'max', 'mean'],
            'DAYS_ENDDATE_FACT': ['min', 'max', 'mean'],
            'AMT_CREDIT_MAX_OVERDUE': ['max', 'mean'],
            'CNT_CREDIT_PROLONG': ['sum'],
            'AMT_CREDIT_SUM': ['max', 'mean', 'sum'],
            'AMT_CREDIT_SUM_DEBT': ['max', 'mean', 'sum'],
            'AMT_CREDIT_SUM_OVERDUE': ['mean'],
            'AMT_CREDIT_SUM_LIMIT': ['mean', 'sum'],
            'AMT_ANNUITY': ['max', 'mean', 'sum'],
            'DAYS_EMPLOYED': ['mean'], # Use days employed from bureau for a new feature
            'CREDIT_DAY_OVERDUE': ['max', 'mean'],
            'SK_ID_CURR': ['count'] # To count number of previous credits
        }
        for col in self.bureau.columns:
            if 'CREDIT_TYPE_' in col or 'CREDIT_ACTIVE_' in col or '_STATUS_' in col:
                bureau_aggregations[col] = ['mean']

        self.bureau_aggregations = self.bureau.groupby('SK_ID_CURR').agg(bureau_aggregations)
        self.bureau_aggregations.columns = ['bureau_' + '_'.join(col).strip() for col in self.bureau_aggregations.columns.values]

        print("Bureau and Bureau Balance data processed.")
        return self.bureau_aggregations

    def _process_previous_application(self):
        """
        Processes previous_application table.
        - One-hot encodes categorical features.
        - Aggregates by SK_ID_CURR.
        """
        print("Processing Previous Application data...")

        # One-hot encode categorical features
        prev_app_categorical_cols = self.previous_application.select_dtypes('object').columns
        self.previous_application = pd.get_dummies(self.previous_application, columns=prev_app_categorical_cols, dummy_na=False)

        # Define aggregations for previous_application
        prev_app_aggregations = {
            'AMT_ANNUITY': ['min', 'max', 'mean'],
            'AMT_APPLICATION': ['min', 'max', 'mean'],
            'AMT_CREDIT': ['min', 'max', 'mean'],
            'AMT_GOODS_PRICE': ['min', 'max', 'mean'],
            'HOUR_APPR_PROCESS_START': ['min', 'max', 'mean'],
            'RATE_DOWN_PAYMENT': ['min', 'max', 'mean'],
            'DAYS_DECISION': ['min', 'max', 'mean'],
            'CNT_PAYMENT': ['mean', 'sum'],
            'SK_ID_CURR': ['count'] # Count number of previous applications
        }
        for col in self.previous_application.columns:
            if 'NAME_CONTRACT_STATUS' in col or 'NAME_YIELD_GROUP' in col or 'PRODUCT_COMBINATION' in col:
                prev_app_aggregations[col] = ['mean']

        self.prev_app_aggregations = self.previous_application.groupby('SK_ID_CURR').agg(prev_app_aggregations)
        self.prev_app_aggregations.columns = ['prev_app_' + '_'.join(col).strip() for col in self.prev_app_aggregations.columns.values]

        print("Previous Application data processed.")
        return self.prev_app_aggregations

    def transform(self, app_train_df, app_test_df):
        """
        Orchestrates the processing of supplementary tables and merges them with application data.
        """
        self._load_data()

        bureau_features = self._process_bureau_and_balance()
        prev_app_features = self._process_previous_application()

        print("Merging supplementary features with application data...")

        # Merge with training data
        app_train_df = app_train_df.merge(bureau_features, on='SK_ID_CURR', how='left')
        app_train_df = app_train_df.merge(prev_app_features, on='SK_ID_CURR', how='left')

        # Merge with test data
        app_test_df = app_test_df.merge(bureau_features, on='SK_ID_CURR', how='left')
        app_test_df = app_test_df.merge(prev_app_features, on='SK_ID_CURR', how='left')

        # Fill NaNs created by merges (for new aggregated features) with 0 or an appropriate value
        # A common strategy is to fill NaNs from aggregated counts/sums with 0, as it means no such record existed.
        # For other numerical aggregates (mean, min, max, var), median/mean imputation might be more appropriate
        # but for simplicity for newly added features, 0 often makes sense if it implies 'absence of activity'.
        # Here, we'll fill numerical NaNs with 0 in the new columns.
        new_bureau_cols = [col for col in bureau_features.columns if col not in app_train_df.columns]
        for col in new_bureau_cols:
            if col in app_train_df.columns and app_train_df[col].dtype in ['float64', 'int64']:
                app_train_df[col].fillna(0, inplace=True)
            if col in app_test_df.columns and app_test_df[col].dtype in ['float64', 'int64']:
                app_test_df[col].fillna(0, inplace=True)

        new_prev_app_cols = [col for col in prev_app_features.columns if col not in app_train_df.columns]
        for col in new_prev_app_cols:
            if col in app_train_df.columns and app_train_df[col].dtype in ['float64', 'int64']:
                app_train_df[col].fillna(0, inplace=True)
            if col in app_test_df.columns and app_test_df[col].dtype in ['float64', 'int64']:
                app_test_df[col].fillna(0, inplace=True)

        print("Supplementary features merged.")
        return app_train_df, app_test_df